/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.zhen.foo;

public class FooModuleJNI {
  public final static native long new_Foo();
  public final static native void delete_Foo(long jarg1);
  public final static native void Foo_useType(long jarg1, Foo jarg1_, String jarg2);
  public final static native long new_Bar();
  public final static native void delete_Bar(long jarg1);
  public final static native void Bar_useType(long jarg1, Bar jarg1_, String jarg2);
  public final static native long new_Baz();
  public final static native void delete_Baz(long jarg1);
  public final static native long Baz_stdStringMap(long jarg1, Baz jarg1_);
  public final static native long Baz_barMap(long jarg1, Baz jarg1_);
  public final static native long Baz_noWrapMap(long jarg1, Baz jarg1_);
  public final static native void Baz_noWrapMapIn(long jarg1, Baz jarg1_, long jarg2, NoWrapMap jarg2_);
  public final static native long new_WrapStringType__SWIG_0();
  public final static native void delete_WrapStringType(long jarg1);
  public final static native long new_WrapStringType__SWIG_1(String jarg1);
  public final static native String WrapStringType_get(long jarg1, WrapStringType jarg1_);
  public final static native long new_NoWrapMap__SWIG_0();
  public final static native long new_NoWrapMap__SWIG_1(long jarg1, NoWrapMap jarg1_);
  public final static native long NoWrapMap_Iterator_getNextUnchecked(long jarg1);
  public final static native boolean NoWrapMap_Iterator_isNot(long jarg1, long jarg2);
  public final static native String NoWrapMap_Iterator_getKey(long jarg1);
  public final static native String NoWrapMap_Iterator_getValue(long jarg1);
  public final static native void NoWrapMap_Iterator_setValue(long jarg1, long jarg2, WrapStringType jarg2_);
  public final static native void delete_NoWrapMap_Iterator(long jarg1);
  public final static native boolean NoWrapMap_isEmpty(long jarg1, NoWrapMap jarg1_);
  public final static native void NoWrapMap_clear(long jarg1, NoWrapMap jarg1_);
  public final static native long NoWrapMap_find(long jarg1, NoWrapMap jarg1_, long jarg2, WrapStringType jarg2_);
  public final static native long NoWrapMap_begin(long jarg1, NoWrapMap jarg1_);
  public final static native long NoWrapMap_end(long jarg1, NoWrapMap jarg1_);
  public final static native int NoWrapMap_sizeImpl(long jarg1, NoWrapMap jarg1_);
  public final static native boolean NoWrapMap_containsImpl(long jarg1, NoWrapMap jarg1_, long jarg2, WrapStringType jarg2_);
  public final static native void NoWrapMap_putUnchecked(long jarg1, NoWrapMap jarg1_, long jarg2, WrapStringType jarg2_, long jarg3, WrapStringType jarg3_);
  public final static native void NoWrapMap_removeUnchecked(long jarg1, NoWrapMap jarg1_, long jarg2);
  public final static native void delete_NoWrapMap(long jarg1);
  public final static native long new_StdStringMap__SWIG_0();
  public final static native long new_StdStringMap__SWIG_1(long jarg1, StdStringMap jarg1_);
  public final static native long StdStringMap_Iterator_getNextUnchecked(long jarg1, StdStringMap.Iterator jarg1_);
  public final static native boolean StdStringMap_Iterator_isNot(long jarg1, StdStringMap.Iterator jarg1_, long jarg2, StdStringMap.Iterator jarg2_);
  public final static native String StdStringMap_Iterator_getKey(long jarg1, StdStringMap.Iterator jarg1_);
  public final static native String StdStringMap_Iterator_getValue(long jarg1, StdStringMap.Iterator jarg1_);
  public final static native void StdStringMap_Iterator_setValue(long jarg1, StdStringMap.Iterator jarg1_, String jarg2);
  public final static native void delete_StdStringMap_Iterator(long jarg1);
  public final static native boolean StdStringMap_isEmpty(long jarg1, StdStringMap jarg1_);
  public final static native void StdStringMap_clear(long jarg1, StdStringMap jarg1_);
  public final static native long StdStringMap_find(long jarg1, StdStringMap jarg1_, String jarg2);
  public final static native long StdStringMap_begin(long jarg1, StdStringMap jarg1_);
  public final static native long StdStringMap_end(long jarg1, StdStringMap jarg1_);
  public final static native int StdStringMap_sizeImpl(long jarg1, StdStringMap jarg1_);
  public final static native boolean StdStringMap_containsImpl(long jarg1, StdStringMap jarg1_, String jarg2);
  public final static native void StdStringMap_putUnchecked(long jarg1, StdStringMap jarg1_, String jarg2, String jarg3);
  public final static native void StdStringMap_removeUnchecked(long jarg1, StdStringMap jarg1_, long jarg2, StdStringMap.Iterator jarg2_);
  public final static native void delete_StdStringMap(long jarg1);
  public final static native long new_BarMap__SWIG_0();
  public final static native long new_BarMap__SWIG_1(long jarg1, BarMap jarg1_);
  public final static native long BarMap_Iterator_getNextUnchecked(long jarg1, BarMap.Iterator jarg1_);
  public final static native boolean BarMap_Iterator_isNot(long jarg1, BarMap.Iterator jarg1_, long jarg2, BarMap.Iterator jarg2_);
  public final static native long BarMap_Iterator_getKey(long jarg1, BarMap.Iterator jarg1_);
  public final static native long BarMap_Iterator_getValue(long jarg1, BarMap.Iterator jarg1_);
  public final static native void BarMap_Iterator_setValue(long jarg1, BarMap.Iterator jarg1_, long jarg2, Bar jarg2_);
  public final static native void delete_BarMap_Iterator(long jarg1);
  public final static native boolean BarMap_isEmpty(long jarg1, BarMap jarg1_);
  public final static native void BarMap_clear(long jarg1, BarMap jarg1_);
  public final static native long BarMap_find(long jarg1, BarMap jarg1_, long jarg2, Bar jarg2_);
  public final static native long BarMap_begin(long jarg1, BarMap jarg1_);
  public final static native long BarMap_end(long jarg1, BarMap jarg1_);
  public final static native int BarMap_sizeImpl(long jarg1, BarMap jarg1_);
  public final static native boolean BarMap_containsImpl(long jarg1, BarMap jarg1_, long jarg2, Bar jarg2_);
  public final static native void BarMap_putUnchecked(long jarg1, BarMap jarg1_, long jarg2, Bar jarg2_, long jarg3, Bar jarg3_);
  public final static native void BarMap_removeUnchecked(long jarg1, BarMap jarg1_, long jarg2, BarMap.Iterator jarg2_);
  public final static native void delete_BarMap(long jarg1);
  public final static native long Baz_SWIGUpcast(long jarg1);
}
