/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.zhen.foo;

public class SWIGTYPE_p_std__mapT_ScalarT_std__string_t_ScalarT_std__string_t_std__lessT_ScalarT_std__string_t_t_t__iterator {
  private transient long swigCPtr;

  protected SWIGTYPE_p_std__mapT_ScalarT_std__string_t_ScalarT_std__string_t_std__lessT_ScalarT_std__string_t_t_t__iterator(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_std__mapT_ScalarT_std__string_t_ScalarT_std__string_t_std__lessT_ScalarT_std__string_t_t_t__iterator() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_std__mapT_ScalarT_std__string_t_ScalarT_std__string_t_std__lessT_ScalarT_std__string_t_t_t__iterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

