/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.zhen.foo;

public class WrapStringType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected WrapStringType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WrapStringType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FooModuleJNI.delete_WrapStringType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public WrapStringType() {
    this(FooModuleJNI.new_WrapStringType__SWIG_0(), true);
  }

  public WrapStringType(String data) {
    this(FooModuleJNI.new_WrapStringType__SWIG_1(data), true);
  }

  public String get() {
    return FooModuleJNI.WrapStringType_get(swigCPtr, this);
  }

}
